# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66effdbc4d1c7122b3089567c47a56b475bc99e5233e4936ef39ac417a57ef1d3067a65060d1ea3f24634b8b8c8ca3531365b4f8f161913cee73fd4c3f75a623

test:
  secret_key_base: 82ddeb496879882e00405e6371d619d34b43a530553f6170d156603540994a40cc58b059b6ea12dd2af54a4b58e8171a0d49a6245dbcb267bd2639a4be5cb2c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
