# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f43d5e4838fd0beb10f4e8bccea2365309e101fe1f333404cd36493f6f126e62e21d943dcba88a450b078e6dd33b70006234128c6c8acbfa99651a1c9a99499

test:
  secret_key_base: 16f15bd3f51035eff0500eb89881a4f61e6b1674ed47d2fc45389d4a151eb388fb3dabc069be46c76645e18c4bd0a8f4ea0ad4c69cd499d6a2f66e4e4462a17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
